[package]
name = "solana-escrow"
version = "0.1.0"
edition = "2021"
# rust-version = "1.81.0"  # Set the required Rust version

[dependencies]
solana-program = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
borsh = "0.9.1"

[lib]
crate-type = ["cdylib", "lib"] 